# Generated by Django 5.2.7 on 2025-11-07 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aula", models.CharField(max_length=200)),
                ("data_prevista", models.DateField(default=django.utils.timezone.now)),
                ("concluida", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Igreja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Diario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_da_aula", models.DateField()),
                ("alunos_presentes", models.IntegerField()),
                ("alunos_ausentes", models.IntegerField()),
                ("numeros_visitantes", models.IntegerField()),
                ("numeros_biblias", models.IntegerField()),
                ("ofertas", models.FloatField()),
                ("dizimos", models.FloatField()),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.aula"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.classe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classe",
            name="igreja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base.igreja"
            ),
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField()),
                (
                    "igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presenca", models.CharField(max_length=8)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.aluno"
                    ),
                ),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.diario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trimestre", models.CharField(max_length=50)),
                ("ano", models.CharField(max_length=50)),
                ("concluido", models.BooleanField(default=False)),
                (
                    "igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.aluno"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.classe"
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.trimestre"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aula",
            name="trimestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base.trimestre"
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
                (
                    "igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.classe"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.usuario"
                    ),
                ),
            ],
        ),
    ]
